export const FAVOURITES_ADD_LAUNCH = 'FAVOURITES_ADD_LAUNCH';
export const FAVOURITES_REMOVE_LAUNCH = 'FAVOURITES_REMOVE_LAUNCH';

export const FAVOURITES_ADD_LAUNCHPAD = 'FAVOURITES_ADD_LAUNCHPAD';
export const FAVOURITES_REMOVE_LAUNCHPAD = 'FAVOURITES_REMOVE_LAUNCHPAD';
